site_name: Jetpack Compose 博物馆
repo_name: Jetpack Compose 博物馆
repo_url: https://github.com/Compose-Museum/Compose-Tutorial
site_url: https://docs.compose.net.cn/
edit_uri: tree/main/docs/

theme:
  name: material
  language: zh
  icon:
    repo: fontawesome/brands/github
  logo: assets/logo.png
  feature:
    - tabs: true
    - instant
    - header.autohide

nav:
  - 'Jetpack Compose':
    - '概述': index.md
    - '在开始之前': start.md
    - '基本组件':
        - 'Text': elements/text.md
        - 'Button': elements/button.md
        - 'Card': elements/card.md
        - 'Icon': elements/icon.md
        - 'Image': elements/image.md
        - 'IconButton': elements/iconbutton.md
        - 'TextField': elements/textfield.md
    - '布局': 
        - '概述': layout/overview.md
        - 'Column': layout/column.md
        - 'ModalBottomSheetLayout': layout/modalbottomsheetlayout.md
        - 'Row': layout/row.md
        - 'Spacer': layout/spacer.md
        - 'Scaffold':
          - '概述': layout/scaffold/overview.md
          - '1. topBar': layout/scaffold/topbar.md
          - '2. bottomBar': layout/scaffold/bottombar.md
          - '3. drawerContent': layout/scaffold/drawercontent.md
          - '4. floatingActionButton': layout/scaffold/floatingactionbutton.md
    - '参数':
        - 'Modifier': parameters/modifier.md
    - '代码实验室': codelabs.md
    - '贡献': contributing.md
    - '资源': resources.md
    - '关于投喂': pay.md
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Compose-Museum/Compose-Tutorial/


markdown_extensions:
  - pymdownx.highlight:
      linenums: false
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.superfences
  - admonition
  - attr_list

plugins:
  - search
  - git-revision-date-localized:
      type: date
